### PR TITLE
Modern Objc Syntax

### PR DESCRIPTION
**Pull request by jstart**
Modern Objc syntax refactor and style cleanup.

### CODE REVIEW

**Comment by fkuehne** [comment]
I cannot merge this patch as is. You are introducing a huge number of white-spacing mistakes. Additionally, please respect the existing coding style of always having the opening bracket on the same line as the expression. If you solve that, I'll be happy to merge your work :)

**Comment by jstart** [comment]
Ah my bad.  I use uncrustify to automatically format my code to a specifc style.  Didn't know this project had a particular style.  I'll remove those changes. Thanks for maintaining this!

**Comment by jstart** [comment]
Removed the original commits, just did the modernization.

**Comment by fkuehne** [comment]
Merged, thanks a lot for your work!

**Pull request merged**
