### PR TITLE
Fix podspec

### PR DESCRIPTION
**Pull request by squarefrog**
I've pushed the pod, but I had to fix the OS X line. I should have submitted this PR last time I pushed!

### CODE REVIEW

**Comment by fkuehne** [comment]
I'll re-tag, no worries :)

**Comment by squarefrog** [comment]
No need to retag - CocoaPods uses the pod spec from the specs repo rather than this one!

**Comment by fkuehne** [comment]
Sure, but I prefer to have tarballs which match the release you get from CocoaPods. So it is done now and the link to the release page on github stays the same.

**Comment by squarefrog** [comment]
:+1: no worries. Have a great weekend Felix!

**Comment by fkuehne** [comment]
Same to you and thanks for your continued maintenance efforts!

**Comment by squarefrog** [comment]
Thank my employer for allowing me to work on it during work hours ;)

**Pull request merged**
